# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 22:34
from __future__ import unicode_literals

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=45, verbose_name=b'Nombre de usuario')),
                ('name', models.CharField(max_length=45, verbose_name=b'Nombre')),
                ('last_name', models.CharField(max_length=45, verbose_name=b'Apellido')),
                ('birth_date', models.DateField(verbose_name=b'Fecha de nacimiento')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name=b'Numero de telefono')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('image_profile', models.ImageField(blank=True, null=True, upload_to=app.models.get_artist_image_path)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name=b'Nombre de la categoria')),
                ('description', models.TextField(blank=True, verbose_name=b'Descripcion de la categoria')),
                ('image_profile', models.ImageField(blank=True, null=True, upload_to=app.models.get_category_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('description', models.TextField(verbose_name=b'Descripcion del evento')),
                ('location', models.CharField(max_length=45)),
                ('date', models.DateTimeField()),
                ('image_profile', models.ImageField(blank=True, null=True, upload_to=app.models.get_event_image_path)),
                ('state', models.CharField(choices=[(b'A', b'Activo'), (b'F', b'Terminado'), (b'C', b'Cancelado')], default=b'A', max_length=1)),
                ('arist', models.ManyToManyField(to='app.Artist')),
                ('categories', models.ManyToManyField(to='app.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('content', models.TextField()),
                ('image_profile', models.ImageField(blank=True, null=True, upload_to=app.models.get_note_image_path)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
                ('genre', models.CharField(choices=[(b'M', b'Masculino'), (b'F', b'Femenino'), (b'O', b'Otro')], max_length=1, null=True)),
                ('arist', models.ManyToManyField(to='app.Artist')),
                ('event', models.ManyToManyField(to='app.Event')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Category'),
        ),
    ]
